// src/components/notes/TableNote.vue
<script setup lang="ts">
import type { TableNoteData } from '../types'

defineProps<{ note: TableNoteData }>()
</script>

<template>
  <table>
    <tbody>
      <tr v-for="(row, rowIndex) in note.rows" :key="rowIndex">
        <template v-for="(cell, cellIndex) in row" :key="cellIndex">
          <td v-if="cellIndex < note.cols">{{ cell }}</td>
        </template>
      </tr>
    </tbody>
  </table>
</template>

// src/components/TableNote/TableNote.tsx
import type { TableNoteData } from "../../types";

export default function TableNote({ note }: { note: TableNoteData }) {
    return (
        <table>
            <tbody>
            {note.rows.map((row, rowIndex) => (
                <tr key={rowIndex}>
                {row.map((cell, cellIndex) => 
                    cellIndex < note.cols && <td key={cellIndex}>{cell}</td>
                )}
                </tr>
            ))}
            </tbody>
        </table>
    )
}
