// src/App.tsx
import { useState } from 'react'
import './App.css'
import { CreateNoteButton } from './components/CreateNoteButton'
import { Note } from './components/Note'
import { NOTE_TYPES } from './types'

function App() {

  const[isFormOpen, setIsFormOpen] = useState(false)

  function createTextNoteHandler() {
    setIsFormOpen(true)
  }

  return (
    <>
      <div className='all-notes'>
        <Note
          id={1}
          title='Text Note'
          tags={new Set<string>().add('tag1').add('tag2')}
          isPinned={true}
          createdAt={20250126}
          type={NOTE_TYPES.TEXT}
          content='First note!'
        />
      </div>
      <nav className='add-note-buttons'>
        <CreateNoteButton
          noteType={NOTE_TYPES.TEXT}
          onCreateNote={createTextNoteHandler} />
        <CreateNoteButton
          noteType={NOTE_TYPES.TABLE}
          onCreateNote={a => a + 1} />
        <CreateNoteButton
          noteType={NOTE_TYPES.IMAGE}
          onCreateNote={a => a + 1} />
      </nav>
      
    </>
  )
}

export default App

// src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import CreateNoteButton from './components/controls/CreateNoteButton.vue'
import EditNoteForm from './components/forms/EditNoteForm.vue'
import Note from './components/notes/Note.vue'
import { NOTE_TYPES, type NoteType } from './types'

const activeForm = ref<NoteType | null>(null)

function createTextNoteHandler() {
  activeForm.value = NOTE_TYPES.TEXT
}

function createTableNoteHandler() {
  activeForm.value = NOTE_TYPES.TABLE
}

function createImageNoteHandler() {
  activeForm.value = NOTE_TYPES.IMAGE
}

function closeForm() {
  activeForm.value = null
}
</script>

<template>
  <div class="all-notes">
    <Note
      title="Text Note"
      content="First note!"
      :id="1"
      :tags="new Set(['tag1', 'tag2'])"
      :isPinned="true"
      :createdAt="20250126"
      :type="NOTE_TYPES.TEXT"
    />
  </div>
  <EditNoteForm v-if="activeForm" :noteType="activeForm" @close="closeForm" />
  <nav class="add-note-buttons">
    <CreateNoteButton :noteType="NOTE_TYPES.TEXT" @createNote="createTextNoteHandler" />
    <CreateNoteButton :noteType="NOTE_TYPES.TABLE" @createNote="createTableNoteHandler" />
    <CreateNoteButton :noteType="NOTE_TYPES.IMAGE" @createNote="createImageNoteHandler" />
  </nav>
</template>
